CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: [0]
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 3
PRINT_FREQ: 10

DATASET:
  DATASET: loveda
  ROOT: data/
  TRAIN_SET: 'list/loveda/train.lst'  # Training list file
  TEST_SET: 'list/loveda/val.lst'  # Validation list file
  NUM_CLASSES: 7  # Update this to match the number of classes in LoveDA

MODEL:
  NAME: 'pidnet_s'
  NUM_OUTPUTS: 2
  PRETRAINED: './pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar'

LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
  
TRAIN:
  IMAGE_SIZE:
  - 1024  # Adjusted to LoveDA dataset resolution
  - 1024
  BASE_SIZE: 1024
  BATCH_SIZE_PER_GPU: 2  # Adjust based on GPU memory
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 20  # Set training epochs to 20
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.005
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
